const {Schema, model, Types} = require('mongoose')

const schema = new Schema({
     name: {type: String, required: true, default: ""},
     series_type: {type: Number, required: true, default: 1},
     win_seriess: {type: String, required: true, default: "false"},
     take_profit: {type: Number, required: true, default: 100},
     stop_loss: {type: Number, required: true, default: 100},
     take_profit_global: {type: Number, required: true, default: 1000},
     stop_loss_global: {type: Number, required: true, default: 1000},
     stop_loss_stake_mult:{type: String, required: true, default: "1.5,2"},
     stop_loss_stake_mult_cnt:{type: Number, required: true, default: 5},
     expire_m: {type: Number, required: true, default: 1},
     price: {type: Number, required: true, default: 0},
     creator_id: {type: String, required: true, default: ""},
     bet: {type: Number, required: true, default: 0.35},
     max_bet: {type: Number, required: true, default: 10000},
     expire: {type: Number, required: true, default: 5},
     expire_t: {type: String, required: true, default: "t"},
     martin: {type: String, required: true, default: "true"},
     mult: {type: Number, required: true, default: 2.5},
     mstep: {type: Number, required: true, default: 5},
     mstart: {type: Number, required: true, default: 0},
     sstep: {type: Number, required: true, default: 2},
     smult: {type: Number, required: true, default: 3},
     martin_alt: {type: String, required: true, default: "false"},
     mult_alt: {type: Number, required: true, default: 2.5},
     mstep_alt: {type: Number, required: true, default: 10},
     mstep_colen_alt: {type: Number, required: true, default: 2},
     addbet: {type: String, required: true, default: "false"},
     stop_loss_cnt: {type: Number, required: true, default: 0},
     stop_loss_cnt_trade: {type: Number, required: true, default: 0},
     trade_type: {type: String, required: true, default: "one trade"},
})

module.exports = model('Strategy', schema)